# on:
#   push:
#     branches:    
#       - main
#   pull_request:

# jobs:
#   build-image:
#     name: Image name
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{secrets.DOCKERHUB_USERNAME}}
#           password: ${{secrets.DOCKERHUB_TOKEN}}

#       - name: Docker Build
#         uses: docker/build-push-action@v2
#         with:
#           push: ${{github.event_name != 'pull_request'}}
#           tags: niko123/httpenv-example-1