on:
  push:
    branches:    
      - main
  pull_request:

jobs:
  build-image:
    name: Image name
    runs-on: ubuntu-22.04
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker Build  
        uses: docker/build-push-action@v3
        with:
          push: ${{github.event_name != 'pull_request'}}
          tags: niko123/httpenv-example-1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          paltforms: linux/amd64,linux/arm64,linux/arm/v7