on:
  push:
    branches:    
      - main
  pull_request:

jobs:
  build-image:
    name: Image name
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: bretfisher/allhands22
          flavor: latest=false
          tags: |
            type=raw,value=04 
            type=raw,value=latest, enable=${{endsWith(github.ref, github.event.repository)}}
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}} 

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Docker Build  
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7